### ISSUE TITLE
Blas GEMM launch failed

### ISSUE THREAD

**Issue by AlexNmSED** [hasibzunair/MoNuSAC-ISBI-2020#17]
Hello, I encountered the problem that Blas GEMM launch failed to start during training. I adjusted the batch size to 32 and it still exists. Do you have any suggestions?

**Comment by AlexNmSED** [comment]
Thank you for your reply. 

2021-04-01 10:45:34.564579: E tensorflow/stream_executor/cuda/cuda_blas.cc:428] failed to run cuBLAS routine: CUBLAS_STATUS_EXECUTION_FAILED
2021-04-01 10:45:34.565131: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Internal: Blas SGEMM launch failed : m=32, n=10, k=40
	 [[{{node block1a_se_reduce/convolution}}]]
Traceback (most recent call last):
  File "3_train.py", line 490, in <module>
    validation_steps=len(valid_dataloader),  # val samples = batch size * no of steps
  File "/home/jack/WorkSpace/Anconda3/envs/MoMuSAC_tf2/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/jack/WorkSpace/Anconda3/envs/MoMuSAC_tf2/lib/python3.6/site-packages/keras/engine/training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/jack/WorkSpace/Anconda3/envs/MoMuSAC_tf2/lib/python3.6/site-packages/keras/engine/training_generator.py", line 220, in fit_generator
    reset_metrics=False)
  File "/home/jack/WorkSpace/Anconda3/envs/MoMuSAC_tf2/lib/python3.6/site-packages/keras/engine/training.py", line 1514, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/jack/WorkSpace/Anconda3/envs/MoMuSAC_tf2/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3741, in __call__
    outputs = self._graph_fn(*converted_inputs)
  File "/home/jack/WorkSpace/Anconda3/envs/MoMuSAC_tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1081, in __call__
    return self._call_impl(args, kwargs)
  File "/home/jack/WorkSpace/Anconda3/envs/MoMuSAC_tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1121, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "/home/jack/WorkSpace/Anconda3/envs/MoMuSAC_tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/home/jack/WorkSpace/Anconda3/envs/MoMuSAC_tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/home/jack/WorkSpace/Anconda3/envs/MoMuSAC_tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError:  Blas SGEMM launch failed : m=32, n=10, k=40
	 [[node block1a_se_reduce/convolution (defined at /home/jack/WorkSpace/Anconda3/envs/MoMuSAC_tf2/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1751) ]] [Op:__inference_keras_scratch_graph_100091]

Function call stack:
keras_scratch_graph

**Comment by hasibzunair** [comment]
Try using a batch size of 1! This is a GPU error. You can also use this to check if it's working https://github.com/hasibzunair/MoNuSAC-ISBI-2020/blob/master/gpu_test.ipynb

**Comment by AlexNmSED** [comment]
Thank you.  But it still doesn't work, I think it may be my cudn version is inconsistent. However, I used your trained model to make predictions. The prediction results are as shown in the picture. I don't know what went wrong. 
![res](https://user-images.githubusercontent.com/42379333/113262122-d2c0cb00-9302-11eb-9089-d5e0b68aeb8c.png)

**Comment by hasibzunair** [comment]
You can use this code when using trained model: https://github.com/hasibzunair/MoNuSAC-ISBI-2020/blob/master/submission/the_great_backpropagator_testing_code.py

**Comment by hasibzunair** [comment]
I've tested it again, works fine. This is an output from https://github.com/hasibzunair/MoNuSAC-ISBI-2020/blob/master/4_inference.ipynb

![image](https://user-images.githubusercontent.com/33185386/113463857-75a64180-93f6-11eb-8bab-307bb0496b37.png)

**Comment by hasibzunair** [comment]
Closing this for  now. Let me know if you have any further issues.
